// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "GELU.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic GELU::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic GELU::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<47> GELU::ap_ST_fsm_state1 = "1";
const sc_lv<47> GELU::ap_ST_fsm_state2 = "10";
const sc_lv<47> GELU::ap_ST_fsm_state3 = "100";
const sc_lv<47> GELU::ap_ST_fsm_state4 = "1000";
const sc_lv<47> GELU::ap_ST_fsm_state5 = "10000";
const sc_lv<47> GELU::ap_ST_fsm_state6 = "100000";
const sc_lv<47> GELU::ap_ST_fsm_state7 = "1000000";
const sc_lv<47> GELU::ap_ST_fsm_state8 = "10000000";
const sc_lv<47> GELU::ap_ST_fsm_state9 = "100000000";
const sc_lv<47> GELU::ap_ST_fsm_state10 = "1000000000";
const sc_lv<47> GELU::ap_ST_fsm_state11 = "10000000000";
const sc_lv<47> GELU::ap_ST_fsm_state12 = "100000000000";
const sc_lv<47> GELU::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<47> GELU::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<32> GELU::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> GELU::ap_const_lv32_4 = "100";
const sc_lv<32> GELU::ap_const_lv32_B = "1011";
const sc_lv<1> GELU::ap_const_lv1_0 = "0";
const sc_lv<32> GELU::ap_const_lv32_28 = "101000";
const sc_lv<32> GELU::ap_const_lv32_29 = "101001";
const sc_lv<32> GELU::ap_const_lv32_2E = "101110";
const int GELU::C_S_AXI_DATA_WIDTH = "100000";
const int GELU::C_M_AXI_GMEM_USER_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int GELU::C_M_AXI_GMEM_PROT_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int GELU::C_M_AXI_GMEM_CACHE_VALUE = "11";
const int GELU::C_M_AXI_DATA_WIDTH = "100000";
const sc_lv<32> GELU::ap_const_lv32_E = "1110";
const sc_lv<32> GELU::ap_const_lv32_11 = "10001";
const sc_lv<32> GELU::ap_const_lv32_14 = "10100";
const sc_lv<32> GELU::ap_const_lv32_1B = "11011";
const sc_lv<32> GELU::ap_const_lv32_18 = "11000";
const sc_lv<32> GELU::ap_const_lv32_21 = "100001";
const sc_lv<32> GELU::ap_const_lv32_1D = "11101";
const sc_lv<32> GELU::ap_const_lv32_22 = "100010";
const sc_lv<32> GELU::ap_const_lv32_27 = "100111";
const sc_lv<32> GELU::ap_const_lv32_1 = "1";
const sc_lv<32> GELU::ap_const_lv32_2 = "10";
const sc_lv<32> GELU::ap_const_lv32_3 = "11";
const sc_lv<8> GELU::ap_const_lv8_0 = "00000000";
const sc_lv<1> GELU::ap_const_lv1_1 = "1";
const sc_lv<20> GELU::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<12> GELU::ap_const_lv12_0 = "000000000000";
const sc_lv<32> GELU::ap_const_lv32_A = "1010";
const sc_lv<32> GELU::ap_const_lv32_1C = "11100";
const sc_lv<3> GELU::ap_const_lv3_0 = "000";
const sc_lv<2> GELU::ap_const_lv2_0 = "00";
const sc_lv<4> GELU::ap_const_lv4_0 = "0000";
const sc_lv<4> GELU::ap_const_lv4_F = "1111";
const sc_lv<32> GELU::ap_const_lv32_3F800000 = "111111100000000000000000000000";
const sc_lv<32> GELU::ap_const_lv32_15 = "10101";
const sc_lv<32> GELU::ap_const_lv32_1E = "11110";
const sc_lv<32> GELU::ap_const_lv32_3D372713 = "111101001101110010011100010011";
const sc_lv<32> GELU::ap_const_lv32_3F4C422A = "111111010011000100001000101010";
const sc_lv<32> GELU::ap_const_lv32_C = "1100";
const sc_lv<32> GELU::ap_const_lv32_F = "1111";
const sc_lv<32> GELU::ap_const_lv32_12 = "10010";
const sc_lv<32> GELU::ap_const_lv32_19 = "11001";
const sc_lv<64> GELU::ap_const_lv64_3FE0000000000000 = "11111111100000000000000000000000000000000000000000000000000000";
const sc_lv<32> GELU::ap_const_lv32_23 = "100011";
const sc_lv<32> GELU::ap_const_lv32_1F = "11111";
const sc_lv<8> GELU::ap_const_lv8_1 = "1";
const sc_lv<12> GELU::ap_const_lv12_1 = "1";
const bool GELU::ap_const_boolean_1 = true;

GELU::GELU(sc_module_name name) : sc_module(name), mVcdFile(0) {
    GELU_AXILiteS_s_axi_U = new GELU_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("GELU_AXILiteS_s_axi_U");
    GELU_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    GELU_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    GELU_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    GELU_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    GELU_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    GELU_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    GELU_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    GELU_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    GELU_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    GELU_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    GELU_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    GELU_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    GELU_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    GELU_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    GELU_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    GELU_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    GELU_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    GELU_AXILiteS_s_axi_U->ACLK(ap_clk);
    GELU_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    GELU_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    GELU_AXILiteS_s_axi_U->ap_start(ap_start);
    GELU_AXILiteS_s_axi_U->interrupt(interrupt);
    GELU_AXILiteS_s_axi_U->ap_ready(ap_ready);
    GELU_AXILiteS_s_axi_U->ap_done(ap_done);
    GELU_AXILiteS_s_axi_U->ap_idle(ap_idle);
    GELU_AXILiteS_s_axi_U->input_width_V(input_width_V);
    GELU_AXILiteS_s_axi_U->input_height_V(input_height_V);
    GELU_AXILiteS_s_axi_U->input_depth_V(input_depth_V);
    GELU_AXILiteS_s_axi_U->in_data(in_data);
    GELU_AXILiteS_s_axi_U->out_data(out_data);
    GELU_gmem_m_axi_U = new GELU_gmem_m_axi<0,32,32,5,16,16,16,16,C_M_AXI_GMEM_ID_WIDTH,C_M_AXI_GMEM_ADDR_WIDTH,C_M_AXI_GMEM_DATA_WIDTH,C_M_AXI_GMEM_AWUSER_WIDTH,C_M_AXI_GMEM_ARUSER_WIDTH,C_M_AXI_GMEM_WUSER_WIDTH,C_M_AXI_GMEM_RUSER_WIDTH,C_M_AXI_GMEM_BUSER_WIDTH,C_M_AXI_GMEM_USER_VALUE,C_M_AXI_GMEM_PROT_VALUE,C_M_AXI_GMEM_CACHE_VALUE>("GELU_gmem_m_axi_U");
    GELU_gmem_m_axi_U->AWVALID(m_axi_gmem_AWVALID);
    GELU_gmem_m_axi_U->AWREADY(m_axi_gmem_AWREADY);
    GELU_gmem_m_axi_U->AWADDR(m_axi_gmem_AWADDR);
    GELU_gmem_m_axi_U->AWID(m_axi_gmem_AWID);
    GELU_gmem_m_axi_U->AWLEN(m_axi_gmem_AWLEN);
    GELU_gmem_m_axi_U->AWSIZE(m_axi_gmem_AWSIZE);
    GELU_gmem_m_axi_U->AWBURST(m_axi_gmem_AWBURST);
    GELU_gmem_m_axi_U->AWLOCK(m_axi_gmem_AWLOCK);
    GELU_gmem_m_axi_U->AWCACHE(m_axi_gmem_AWCACHE);
    GELU_gmem_m_axi_U->AWPROT(m_axi_gmem_AWPROT);
    GELU_gmem_m_axi_U->AWQOS(m_axi_gmem_AWQOS);
    GELU_gmem_m_axi_U->AWREGION(m_axi_gmem_AWREGION);
    GELU_gmem_m_axi_U->AWUSER(m_axi_gmem_AWUSER);
    GELU_gmem_m_axi_U->WVALID(m_axi_gmem_WVALID);
    GELU_gmem_m_axi_U->WREADY(m_axi_gmem_WREADY);
    GELU_gmem_m_axi_U->WDATA(m_axi_gmem_WDATA);
    GELU_gmem_m_axi_U->WSTRB(m_axi_gmem_WSTRB);
    GELU_gmem_m_axi_U->WLAST(m_axi_gmem_WLAST);
    GELU_gmem_m_axi_U->WID(m_axi_gmem_WID);
    GELU_gmem_m_axi_U->WUSER(m_axi_gmem_WUSER);
    GELU_gmem_m_axi_U->ARVALID(m_axi_gmem_ARVALID);
    GELU_gmem_m_axi_U->ARREADY(m_axi_gmem_ARREADY);
    GELU_gmem_m_axi_U->ARADDR(m_axi_gmem_ARADDR);
    GELU_gmem_m_axi_U->ARID(m_axi_gmem_ARID);
    GELU_gmem_m_axi_U->ARLEN(m_axi_gmem_ARLEN);
    GELU_gmem_m_axi_U->ARSIZE(m_axi_gmem_ARSIZE);
    GELU_gmem_m_axi_U->ARBURST(m_axi_gmem_ARBURST);
    GELU_gmem_m_axi_U->ARLOCK(m_axi_gmem_ARLOCK);
    GELU_gmem_m_axi_U->ARCACHE(m_axi_gmem_ARCACHE);
    GELU_gmem_m_axi_U->ARPROT(m_axi_gmem_ARPROT);
    GELU_gmem_m_axi_U->ARQOS(m_axi_gmem_ARQOS);
    GELU_gmem_m_axi_U->ARREGION(m_axi_gmem_ARREGION);
    GELU_gmem_m_axi_U->ARUSER(m_axi_gmem_ARUSER);
    GELU_gmem_m_axi_U->RVALID(m_axi_gmem_RVALID);
    GELU_gmem_m_axi_U->RREADY(m_axi_gmem_RREADY);
    GELU_gmem_m_axi_U->RDATA(m_axi_gmem_RDATA);
    GELU_gmem_m_axi_U->RLAST(m_axi_gmem_RLAST);
    GELU_gmem_m_axi_U->RID(m_axi_gmem_RID);
    GELU_gmem_m_axi_U->RUSER(m_axi_gmem_RUSER);
    GELU_gmem_m_axi_U->RRESP(m_axi_gmem_RRESP);
    GELU_gmem_m_axi_U->BVALID(m_axi_gmem_BVALID);
    GELU_gmem_m_axi_U->BREADY(m_axi_gmem_BREADY);
    GELU_gmem_m_axi_U->BRESP(m_axi_gmem_BRESP);
    GELU_gmem_m_axi_U->BID(m_axi_gmem_BID);
    GELU_gmem_m_axi_U->BUSER(m_axi_gmem_BUSER);
    GELU_gmem_m_axi_U->ACLK(ap_clk);
    GELU_gmem_m_axi_U->ARESET(ap_rst_n_inv);
    GELU_gmem_m_axi_U->ACLK_EN(ap_var_for_const0);
    GELU_gmem_m_axi_U->I_ARVALID(gmem_ARVALID);
    GELU_gmem_m_axi_U->I_ARREADY(gmem_ARREADY);
    GELU_gmem_m_axi_U->I_ARADDR(gmem_addr_reg_476);
    GELU_gmem_m_axi_U->I_ARID(ap_var_for_const1);
    GELU_gmem_m_axi_U->I_ARLEN(tmp_3_reg_434);
    GELU_gmem_m_axi_U->I_ARSIZE(ap_var_for_const2);
    GELU_gmem_m_axi_U->I_ARLOCK(ap_var_for_const3);
    GELU_gmem_m_axi_U->I_ARCACHE(ap_var_for_const4);
    GELU_gmem_m_axi_U->I_ARQOS(ap_var_for_const4);
    GELU_gmem_m_axi_U->I_ARPROT(ap_var_for_const2);
    GELU_gmem_m_axi_U->I_ARUSER(ap_var_for_const1);
    GELU_gmem_m_axi_U->I_ARBURST(ap_var_for_const3);
    GELU_gmem_m_axi_U->I_ARREGION(ap_var_for_const4);
    GELU_gmem_m_axi_U->I_RVALID(gmem_RVALID);
    GELU_gmem_m_axi_U->I_RREADY(gmem_RREADY);
    GELU_gmem_m_axi_U->I_RDATA(gmem_RDATA);
    GELU_gmem_m_axi_U->I_RID(gmem_RID);
    GELU_gmem_m_axi_U->I_RUSER(gmem_RUSER);
    GELU_gmem_m_axi_U->I_RRESP(gmem_RRESP);
    GELU_gmem_m_axi_U->I_RLAST(gmem_RLAST);
    GELU_gmem_m_axi_U->I_AWVALID(gmem_AWVALID);
    GELU_gmem_m_axi_U->I_AWREADY(gmem_AWREADY);
    GELU_gmem_m_axi_U->I_AWADDR(gmem_addr_1_reg_498);
    GELU_gmem_m_axi_U->I_AWID(ap_var_for_const1);
    GELU_gmem_m_axi_U->I_AWLEN(ap_var_for_const5);
    GELU_gmem_m_axi_U->I_AWSIZE(ap_var_for_const2);
    GELU_gmem_m_axi_U->I_AWLOCK(ap_var_for_const3);
    GELU_gmem_m_axi_U->I_AWCACHE(ap_var_for_const4);
    GELU_gmem_m_axi_U->I_AWQOS(ap_var_for_const4);
    GELU_gmem_m_axi_U->I_AWPROT(ap_var_for_const2);
    GELU_gmem_m_axi_U->I_AWUSER(ap_var_for_const1);
    GELU_gmem_m_axi_U->I_AWBURST(ap_var_for_const3);
    GELU_gmem_m_axi_U->I_AWREGION(ap_var_for_const4);
    GELU_gmem_m_axi_U->I_WVALID(gmem_WVALID);
    GELU_gmem_m_axi_U->I_WREADY(gmem_WREADY);
    GELU_gmem_m_axi_U->I_WDATA(tmp_42_reg_509);
    GELU_gmem_m_axi_U->I_WID(ap_var_for_const1);
    GELU_gmem_m_axi_U->I_WUSER(ap_var_for_const1);
    GELU_gmem_m_axi_U->I_WLAST(ap_var_for_const6);
    GELU_gmem_m_axi_U->I_WSTRB(ap_var_for_const7);
    GELU_gmem_m_axi_U->I_BVALID(gmem_BVALID);
    GELU_gmem_m_axi_U->I_BREADY(gmem_BREADY);
    GELU_gmem_m_axi_U->I_BRESP(gmem_BRESP);
    GELU_gmem_m_axi_U->I_BID(gmem_BID);
    GELU_gmem_m_axi_U->I_BUSER(gmem_BUSER);
    grp_generic_tanh_float_s_fu_212 = new generic_tanh_float_s("grp_generic_tanh_float_s_fu_212");
    grp_generic_tanh_float_s_fu_212->ap_clk(ap_clk);
    grp_generic_tanh_float_s_fu_212->ap_rst(ap_rst_n_inv);
    grp_generic_tanh_float_s_fu_212->ap_start(grp_generic_tanh_float_s_fu_212_ap_start);
    grp_generic_tanh_float_s_fu_212->ap_done(grp_generic_tanh_float_s_fu_212_ap_done);
    grp_generic_tanh_float_s_fu_212->ap_idle(grp_generic_tanh_float_s_fu_212_ap_idle);
    grp_generic_tanh_float_s_fu_212->ap_ready(grp_generic_tanh_float_s_fu_212_ap_ready);
    grp_generic_tanh_float_s_fu_212->t_in(reg_245);
    grp_generic_tanh_float_s_fu_212->ap_return(grp_generic_tanh_float_s_fu_212_ap_return);
    GELU_fadd_32ns_32ncg_U24 = new GELU_fadd_32ns_32ncg<1,4,32,32,32>("GELU_fadd_32ns_32ncg_U24");
    GELU_fadd_32ns_32ncg_U24->clk(ap_clk);
    GELU_fadd_32ns_32ncg_U24->reset(ap_rst_n_inv);
    GELU_fadd_32ns_32ncg_U24->din0(grp_fu_223_p0);
    GELU_fadd_32ns_32ncg_U24->din1(grp_fu_223_p1);
    GELU_fadd_32ns_32ncg_U24->ce(ap_var_for_const0);
    GELU_fadd_32ns_32ncg_U24->dout(grp_fu_223_p2);
    GELU_fmul_32ns_32hbi_U25 = new GELU_fmul_32ns_32hbi<1,3,32,32,32>("GELU_fmul_32ns_32hbi_U25");
    GELU_fmul_32ns_32hbi_U25->clk(ap_clk);
    GELU_fmul_32ns_32hbi_U25->reset(ap_rst_n_inv);
    GELU_fmul_32ns_32hbi_U25->din0(grp_fu_228_p0);
    GELU_fmul_32ns_32hbi_U25->din1(grp_fu_228_p1);
    GELU_fmul_32ns_32hbi_U25->ce(ap_var_for_const0);
    GELU_fmul_32ns_32hbi_U25->dout(grp_fu_228_p2);
    GELU_fptrunc_64nsjbC_U26 = new GELU_fptrunc_64nsjbC<1,1,64,32>("GELU_fptrunc_64nsjbC_U26");
    GELU_fptrunc_64nsjbC_U26->din0(reg_264);
    GELU_fptrunc_64nsjbC_U26->dout(tmp_42_fu_234_p1);
    GELU_fpext_32ns_6kbM_U27 = new GELU_fpext_32ns_6kbM<1,1,32,64>("GELU_fpext_32ns_6kbM_U27");
    GELU_fpext_32ns_6kbM_U27->din0(grp_fu_237_p0);
    GELU_fpext_32ns_6kbM_U27->dout(grp_fu_237_p1);
    GELU_dmul_64ns_64ocq_U28 = new GELU_dmul_64ns_64ocq<1,5,64,64,64>("GELU_dmul_64ns_64ocq_U28");
    GELU_dmul_64ns_64ocq_U28->clk(ap_clk);
    GELU_dmul_64ns_64ocq_U28->reset(ap_rst_n_inv);
    GELU_dmul_64ns_64ocq_U28->din0(grp_fu_240_p0);
    GELU_dmul_64ns_64ocq_U28->din1(grp_fu_240_p1);
    GELU_dmul_64ns_64ocq_U28->ce(ap_var_for_const0);
    GELU_dmul_64ns_64ocq_U28->dout(grp_fu_240_p2);
    GELU_mul_mul_12nspcA_U29 = new GELU_mul_mul_12nspcA<1,1,12,20,32>("GELU_mul_mul_12nspcA_U29");
    GELU_mul_mul_12nspcA_U29->din0(tmp1_fu_403_p0);
    GELU_mul_mul_12nspcA_U29->din1(tmp1_fu_403_p1);
    GELU_mul_mul_12nspcA_U29->dout(tmp1_fu_403_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state30);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state34);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state35);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state36);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state40);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state41);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state47);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state12);
    sensitive << ( exitcond_fu_368_p2 );
    sensitive << ( gmem_RVALID );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_311_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_311_p2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_ioackin_gmem_ARREADY);
    sensitive << ( gmem_ARREADY );
    sensitive << ( ap_reg_ioackin_gmem_ARREADY );

    SC_METHOD(thread_ap_sig_ioackin_gmem_AWREADY);
    sensitive << ( gmem_AWREADY );
    sensitive << ( ap_reg_ioackin_gmem_AWREADY );

    SC_METHOD(thread_ap_sig_ioackin_gmem_WREADY);
    sensitive << ( gmem_WREADY );
    sensitive << ( ap_reg_ioackin_gmem_WREADY );

    SC_METHOD(thread_d_fu_316_p2);
    sensitive << ( i_op_assign_reg_167 );

    SC_METHOD(thread_exitcond1_fu_326_p2);
    sensitive << ( input_height_V_read_reg_414 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_op_assign_1_reg_190 );

    SC_METHOD(thread_exitcond2_fu_311_p2);
    sensitive << ( input_depth_V_read_reg_409 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_op_assign_reg_167 );

    SC_METHOD(thread_exitcond_fu_368_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( exitcond_fu_368_p2 );
    sensitive << ( gmem_RVALID );
    sensitive << ( input_width_V_read_reg_419 );
    sensitive << ( i_op_assign_2_reg_201 );

    SC_METHOD(thread_gmem_ARVALID);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_reg_ioackin_gmem_ARREADY );

    SC_METHOD(thread_gmem_AWVALID);
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( ap_reg_ioackin_gmem_AWREADY );

    SC_METHOD(thread_gmem_BREADY);
    sensitive << ( ap_CS_fsm_state47 );
    sensitive << ( gmem_BVALID );

    SC_METHOD(thread_gmem_RREADY);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( exitcond_fu_368_p2 );
    sensitive << ( gmem_RVALID );

    SC_METHOD(thread_gmem_WVALID);
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( ap_reg_ioackin_gmem_WREADY );

    SC_METHOD(thread_gmem_blk_n_AR);
    sensitive << ( m_axi_gmem_ARREADY );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_gmem_blk_n_AW);
    sensitive << ( m_axi_gmem_AWREADY );
    sensitive << ( ap_CS_fsm_state41 );

    SC_METHOD(thread_gmem_blk_n_B);
    sensitive << ( m_axi_gmem_BVALID );
    sensitive << ( ap_CS_fsm_state47 );

    SC_METHOD(thread_gmem_blk_n_R);
    sensitive << ( m_axi_gmem_RVALID );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( exitcond_fu_368_p2 );

    SC_METHOD(thread_gmem_blk_n_W);
    sensitive << ( m_axi_gmem_WREADY );
    sensitive << ( ap_CS_fsm_state42 );

    SC_METHOD(thread_grp_fu_223_p0);
    sensitive << ( x_reg_490 );
    sensitive << ( tanh_val_reg_504 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_grp_fu_223_p1);
    sensitive << ( reg_245 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_grp_fu_228_p0);
    sensitive << ( reg_245 );
    sensitive << ( reg_252 );
    sensitive << ( x_reg_490 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_grp_fu_228_p1);
    sensitive << ( x_reg_490 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_grp_fu_237_p0);
    sensitive << ( reg_252 );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state35 );
    sensitive << ( x_reg_490 );

    SC_METHOD(thread_grp_fu_240_p0);
    sensitive << ( reg_258 );
    sensitive << ( reg_264 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state36 );

    SC_METHOD(thread_grp_fu_240_p1);
    sensitive << ( reg_258 );
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( ap_CS_fsm_state36 );

    SC_METHOD(thread_grp_generic_tanh_float_s_fu_212_ap_start);
    sensitive << ( grp_generic_tanh_float_s_fu_212_ap_start_reg );

    SC_METHOD(thread_h_fu_331_p2);
    sensitive << ( i_op_assign_1_reg_190 );

    SC_METHOD(thread_i_op_assign_1_cast2_fu_322_p1);
    sensitive << ( i_op_assign_1_reg_190 );

    SC_METHOD(thread_i_op_assign_2_cast1_fu_364_p1);
    sensitive << ( i_op_assign_2_reg_201 );

    SC_METHOD(thread_in_data2_sum_cast_fu_354_p1);
    sensitive << ( in_data2_sum_fu_349_p2 );

    SC_METHOD(thread_in_data2_sum_fu_349_p2);
    sensitive << ( tmp_15_cast_reg_429 );
    sensitive << ( tmp_44_cast_fu_346_p1 );

    SC_METHOD(thread_index_fu_379_p2);
    sensitive << ( tmp1_reg_471 );
    sensitive << ( i_op_assign_2_cast1_fu_364_p1 );

    SC_METHOD(thread_next_mul_fu_306_p2);
    sensitive << ( tmp_4_cast4_reg_440 );
    sensitive << ( phi_mul_reg_178 );

    SC_METHOD(thread_out_data4_sum6_cast_fu_393_p1);
    sensitive << ( out_data4_sum6_fu_388_p2 );

    SC_METHOD(thread_out_data4_sum6_fu_388_p2);
    sensitive << ( tmp_14_cast_reg_424 );
    sensitive << ( tmp_34_cast_fu_384_p1 );

    SC_METHOD(thread_tmp1_fu_403_p0);
    sensitive << ( tmp_3_reg_434 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_tmp1_fu_403_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp1_fu_403_p10 );

    SC_METHOD(thread_tmp1_fu_403_p10);
    sensitive << ( tmp_reg_466 );

    SC_METHOD(thread_tmp_14_cast_fu_280_p1);
    sensitive << ( tmp_49_fu_270_p4 );

    SC_METHOD(thread_tmp_15_cast_fu_294_p1);
    sensitive << ( tmp_50_fu_284_p4 );

    SC_METHOD(thread_tmp_34_cast_fu_384_p1);
    sensitive << ( index_fu_379_p2 );

    SC_METHOD(thread_tmp_3_fu_298_p1);
    sensitive << ( input_width_V );

    SC_METHOD(thread_tmp_44_cast_fu_346_p1);
    sensitive << ( tmp1_fu_403_p2 );

    SC_METHOD(thread_tmp_49_fu_270_p4);
    sensitive << ( out_data );

    SC_METHOD(thread_tmp_4_cast4_fu_302_p1);
    sensitive << ( input_height_V );

    SC_METHOD(thread_tmp_50_fu_284_p4);
    sensitive << ( in_data );

    SC_METHOD(thread_tmp_fu_337_p2);
    sensitive << ( phi_mul_reg_178 );
    sensitive << ( i_op_assign_1_cast2_fu_322_p1 );

    SC_METHOD(thread_w_fu_373_p2);
    sensitive << ( i_op_assign_2_reg_201 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( exitcond_fu_368_p2 );
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( ap_CS_fsm_state47 );
    sensitive << ( gmem_RVALID );
    sensitive << ( gmem_BVALID );
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( grp_generic_tanh_float_s_fu_212_ap_done );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond1_fu_326_p2 );
    sensitive << ( ap_sig_ioackin_gmem_AWREADY );
    sensitive << ( exitcond2_fu_311_p2 );
    sensitive << ( ap_sig_ioackin_gmem_ARREADY );
    sensitive << ( ap_sig_ioackin_gmem_WREADY );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const6);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const5);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const4);

    SC_THREAD(thread_ap_var_for_const7);

    ap_CS_fsm = "00000000000000000000000000000000000000000000001";
    grp_generic_tanh_float_s_fu_212_ap_start_reg = SC_LOGIC_0;
    ap_reg_ioackin_gmem_ARREADY = SC_LOGIC_0;
    ap_reg_ioackin_gmem_AWREADY = SC_LOGIC_0;
    ap_reg_ioackin_gmem_WREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "GELU_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, m_axi_gmem_AWVALID, "(port)m_axi_gmem_AWVALID");
    sc_trace(mVcdFile, m_axi_gmem_AWREADY, "(port)m_axi_gmem_AWREADY");
    sc_trace(mVcdFile, m_axi_gmem_AWADDR, "(port)m_axi_gmem_AWADDR");
    sc_trace(mVcdFile, m_axi_gmem_AWID, "(port)m_axi_gmem_AWID");
    sc_trace(mVcdFile, m_axi_gmem_AWLEN, "(port)m_axi_gmem_AWLEN");
    sc_trace(mVcdFile, m_axi_gmem_AWSIZE, "(port)m_axi_gmem_AWSIZE");
    sc_trace(mVcdFile, m_axi_gmem_AWBURST, "(port)m_axi_gmem_AWBURST");
    sc_trace(mVcdFile, m_axi_gmem_AWLOCK, "(port)m_axi_gmem_AWLOCK");
    sc_trace(mVcdFile, m_axi_gmem_AWCACHE, "(port)m_axi_gmem_AWCACHE");
    sc_trace(mVcdFile, m_axi_gmem_AWPROT, "(port)m_axi_gmem_AWPROT");
    sc_trace(mVcdFile, m_axi_gmem_AWQOS, "(port)m_axi_gmem_AWQOS");
    sc_trace(mVcdFile, m_axi_gmem_AWREGION, "(port)m_axi_gmem_AWREGION");
    sc_trace(mVcdFile, m_axi_gmem_AWUSER, "(port)m_axi_gmem_AWUSER");
    sc_trace(mVcdFile, m_axi_gmem_WVALID, "(port)m_axi_gmem_WVALID");
    sc_trace(mVcdFile, m_axi_gmem_WREADY, "(port)m_axi_gmem_WREADY");
    sc_trace(mVcdFile, m_axi_gmem_WDATA, "(port)m_axi_gmem_WDATA");
    sc_trace(mVcdFile, m_axi_gmem_WSTRB, "(port)m_axi_gmem_WSTRB");
    sc_trace(mVcdFile, m_axi_gmem_WLAST, "(port)m_axi_gmem_WLAST");
    sc_trace(mVcdFile, m_axi_gmem_WID, "(port)m_axi_gmem_WID");
    sc_trace(mVcdFile, m_axi_gmem_WUSER, "(port)m_axi_gmem_WUSER");
    sc_trace(mVcdFile, m_axi_gmem_ARVALID, "(port)m_axi_gmem_ARVALID");
    sc_trace(mVcdFile, m_axi_gmem_ARREADY, "(port)m_axi_gmem_ARREADY");
    sc_trace(mVcdFile, m_axi_gmem_ARADDR, "(port)m_axi_gmem_ARADDR");
    sc_trace(mVcdFile, m_axi_gmem_ARID, "(port)m_axi_gmem_ARID");
    sc_trace(mVcdFile, m_axi_gmem_ARLEN, "(port)m_axi_gmem_ARLEN");
    sc_trace(mVcdFile, m_axi_gmem_ARSIZE, "(port)m_axi_gmem_ARSIZE");
    sc_trace(mVcdFile, m_axi_gmem_ARBURST, "(port)m_axi_gmem_ARBURST");
    sc_trace(mVcdFile, m_axi_gmem_ARLOCK, "(port)m_axi_gmem_ARLOCK");
    sc_trace(mVcdFile, m_axi_gmem_ARCACHE, "(port)m_axi_gmem_ARCACHE");
    sc_trace(mVcdFile, m_axi_gmem_ARPROT, "(port)m_axi_gmem_ARPROT");
    sc_trace(mVcdFile, m_axi_gmem_ARQOS, "(port)m_axi_gmem_ARQOS");
    sc_trace(mVcdFile, m_axi_gmem_ARREGION, "(port)m_axi_gmem_ARREGION");
    sc_trace(mVcdFile, m_axi_gmem_ARUSER, "(port)m_axi_gmem_ARUSER");
    sc_trace(mVcdFile, m_axi_gmem_RVALID, "(port)m_axi_gmem_RVALID");
    sc_trace(mVcdFile, m_axi_gmem_RREADY, "(port)m_axi_gmem_RREADY");
    sc_trace(mVcdFile, m_axi_gmem_RDATA, "(port)m_axi_gmem_RDATA");
    sc_trace(mVcdFile, m_axi_gmem_RLAST, "(port)m_axi_gmem_RLAST");
    sc_trace(mVcdFile, m_axi_gmem_RID, "(port)m_axi_gmem_RID");
    sc_trace(mVcdFile, m_axi_gmem_RUSER, "(port)m_axi_gmem_RUSER");
    sc_trace(mVcdFile, m_axi_gmem_RRESP, "(port)m_axi_gmem_RRESP");
    sc_trace(mVcdFile, m_axi_gmem_BVALID, "(port)m_axi_gmem_BVALID");
    sc_trace(mVcdFile, m_axi_gmem_BREADY, "(port)m_axi_gmem_BREADY");
    sc_trace(mVcdFile, m_axi_gmem_BRESP, "(port)m_axi_gmem_BRESP");
    sc_trace(mVcdFile, m_axi_gmem_BID, "(port)m_axi_gmem_BID");
    sc_trace(mVcdFile, m_axi_gmem_BUSER, "(port)m_axi_gmem_BUSER");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, input_width_V, "input_width_V");
    sc_trace(mVcdFile, input_height_V, "input_height_V");
    sc_trace(mVcdFile, input_depth_V, "input_depth_V");
    sc_trace(mVcdFile, in_data, "in_data");
    sc_trace(mVcdFile, out_data, "out_data");
    sc_trace(mVcdFile, gmem_blk_n_AR, "gmem_blk_n_AR");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, gmem_blk_n_R, "gmem_blk_n_R");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, exitcond_fu_368_p2, "exitcond_fu_368_p2");
    sc_trace(mVcdFile, gmem_blk_n_AW, "gmem_blk_n_AW");
    sc_trace(mVcdFile, ap_CS_fsm_state41, "ap_CS_fsm_state41");
    sc_trace(mVcdFile, gmem_blk_n_W, "gmem_blk_n_W");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, gmem_blk_n_B, "gmem_blk_n_B");
    sc_trace(mVcdFile, ap_CS_fsm_state47, "ap_CS_fsm_state47");
    sc_trace(mVcdFile, gmem_AWVALID, "gmem_AWVALID");
    sc_trace(mVcdFile, gmem_AWREADY, "gmem_AWREADY");
    sc_trace(mVcdFile, gmem_WVALID, "gmem_WVALID");
    sc_trace(mVcdFile, gmem_WREADY, "gmem_WREADY");
    sc_trace(mVcdFile, gmem_ARVALID, "gmem_ARVALID");
    sc_trace(mVcdFile, gmem_ARREADY, "gmem_ARREADY");
    sc_trace(mVcdFile, gmem_RVALID, "gmem_RVALID");
    sc_trace(mVcdFile, gmem_RREADY, "gmem_RREADY");
    sc_trace(mVcdFile, gmem_RDATA, "gmem_RDATA");
    sc_trace(mVcdFile, gmem_RLAST, "gmem_RLAST");
    sc_trace(mVcdFile, gmem_RID, "gmem_RID");
    sc_trace(mVcdFile, gmem_RUSER, "gmem_RUSER");
    sc_trace(mVcdFile, gmem_RRESP, "gmem_RRESP");
    sc_trace(mVcdFile, gmem_BVALID, "gmem_BVALID");
    sc_trace(mVcdFile, gmem_BREADY, "gmem_BREADY");
    sc_trace(mVcdFile, gmem_BRESP, "gmem_BRESP");
    sc_trace(mVcdFile, gmem_BID, "gmem_BID");
    sc_trace(mVcdFile, gmem_BUSER, "gmem_BUSER");
    sc_trace(mVcdFile, grp_fu_228_p2, "grp_fu_228_p2");
    sc_trace(mVcdFile, reg_245, "reg_245");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, grp_fu_223_p2, "grp_fu_223_p2");
    sc_trace(mVcdFile, reg_252, "reg_252");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, ap_CS_fsm_state34, "ap_CS_fsm_state34");
    sc_trace(mVcdFile, grp_fu_237_p1, "grp_fu_237_p1");
    sc_trace(mVcdFile, reg_258, "reg_258");
    sc_trace(mVcdFile, ap_CS_fsm_state30, "ap_CS_fsm_state30");
    sc_trace(mVcdFile, grp_generic_tanh_float_s_fu_212_ap_ready, "grp_generic_tanh_float_s_fu_212_ap_ready");
    sc_trace(mVcdFile, grp_generic_tanh_float_s_fu_212_ap_done, "grp_generic_tanh_float_s_fu_212_ap_done");
    sc_trace(mVcdFile, ap_CS_fsm_state35, "ap_CS_fsm_state35");
    sc_trace(mVcdFile, grp_fu_240_p2, "grp_fu_240_p2");
    sc_trace(mVcdFile, reg_264, "reg_264");
    sc_trace(mVcdFile, ap_CS_fsm_state40, "ap_CS_fsm_state40");
    sc_trace(mVcdFile, input_depth_V_read_reg_409, "input_depth_V_read_reg_409");
    sc_trace(mVcdFile, input_height_V_read_reg_414, "input_height_V_read_reg_414");
    sc_trace(mVcdFile, input_width_V_read_reg_419, "input_width_V_read_reg_419");
    sc_trace(mVcdFile, tmp_14_cast_fu_280_p1, "tmp_14_cast_fu_280_p1");
    sc_trace(mVcdFile, tmp_14_cast_reg_424, "tmp_14_cast_reg_424");
    sc_trace(mVcdFile, tmp_15_cast_fu_294_p1, "tmp_15_cast_fu_294_p1");
    sc_trace(mVcdFile, tmp_15_cast_reg_429, "tmp_15_cast_reg_429");
    sc_trace(mVcdFile, tmp_3_fu_298_p1, "tmp_3_fu_298_p1");
    sc_trace(mVcdFile, tmp_3_reg_434, "tmp_3_reg_434");
    sc_trace(mVcdFile, tmp_4_cast4_fu_302_p1, "tmp_4_cast4_fu_302_p1");
    sc_trace(mVcdFile, tmp_4_cast4_reg_440, "tmp_4_cast4_reg_440");
    sc_trace(mVcdFile, next_mul_fu_306_p2, "next_mul_fu_306_p2");
    sc_trace(mVcdFile, next_mul_reg_445, "next_mul_reg_445");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, d_fu_316_p2, "d_fu_316_p2");
    sc_trace(mVcdFile, d_reg_453, "d_reg_453");
    sc_trace(mVcdFile, h_fu_331_p2, "h_fu_331_p2");
    sc_trace(mVcdFile, h_reg_461, "h_reg_461");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_fu_337_p2, "tmp_fu_337_p2");
    sc_trace(mVcdFile, tmp_reg_466, "tmp_reg_466");
    sc_trace(mVcdFile, exitcond1_fu_326_p2, "exitcond1_fu_326_p2");
    sc_trace(mVcdFile, tmp1_fu_403_p2, "tmp1_fu_403_p2");
    sc_trace(mVcdFile, tmp1_reg_471, "tmp1_reg_471");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, gmem_addr_reg_476, "gmem_addr_reg_476");
    sc_trace(mVcdFile, w_fu_373_p2, "w_fu_373_p2");
    sc_trace(mVcdFile, w_reg_485, "w_reg_485");
    sc_trace(mVcdFile, ap_block_state12, "ap_block_state12");
    sc_trace(mVcdFile, x_reg_490, "x_reg_490");
    sc_trace(mVcdFile, gmem_addr_1_reg_498, "gmem_addr_1_reg_498");
    sc_trace(mVcdFile, grp_generic_tanh_float_s_fu_212_ap_return, "grp_generic_tanh_float_s_fu_212_ap_return");
    sc_trace(mVcdFile, tanh_val_reg_504, "tanh_val_reg_504");
    sc_trace(mVcdFile, tmp_42_fu_234_p1, "tmp_42_fu_234_p1");
    sc_trace(mVcdFile, tmp_42_reg_509, "tmp_42_reg_509");
    sc_trace(mVcdFile, ap_sig_ioackin_gmem_AWREADY, "ap_sig_ioackin_gmem_AWREADY");
    sc_trace(mVcdFile, grp_generic_tanh_float_s_fu_212_ap_start, "grp_generic_tanh_float_s_fu_212_ap_start");
    sc_trace(mVcdFile, grp_generic_tanh_float_s_fu_212_ap_idle, "grp_generic_tanh_float_s_fu_212_ap_idle");
    sc_trace(mVcdFile, i_op_assign_reg_167, "i_op_assign_reg_167");
    sc_trace(mVcdFile, phi_mul_reg_178, "phi_mul_reg_178");
    sc_trace(mVcdFile, i_op_assign_1_reg_190, "i_op_assign_1_reg_190");
    sc_trace(mVcdFile, exitcond2_fu_311_p2, "exitcond2_fu_311_p2");
    sc_trace(mVcdFile, i_op_assign_2_reg_201, "i_op_assign_2_reg_201");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, grp_generic_tanh_float_s_fu_212_ap_start_reg, "grp_generic_tanh_float_s_fu_212_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, in_data2_sum_cast_fu_354_p1, "in_data2_sum_cast_fu_354_p1");
    sc_trace(mVcdFile, out_data4_sum6_cast_fu_393_p1, "out_data4_sum6_cast_fu_393_p1");
    sc_trace(mVcdFile, ap_reg_ioackin_gmem_ARREADY, "ap_reg_ioackin_gmem_ARREADY");
    sc_trace(mVcdFile, ap_sig_ioackin_gmem_ARREADY, "ap_sig_ioackin_gmem_ARREADY");
    sc_trace(mVcdFile, ap_reg_ioackin_gmem_AWREADY, "ap_reg_ioackin_gmem_AWREADY");
    sc_trace(mVcdFile, ap_reg_ioackin_gmem_WREADY, "ap_reg_ioackin_gmem_WREADY");
    sc_trace(mVcdFile, ap_sig_ioackin_gmem_WREADY, "ap_sig_ioackin_gmem_WREADY");
    sc_trace(mVcdFile, grp_fu_223_p0, "grp_fu_223_p0");
    sc_trace(mVcdFile, grp_fu_223_p1, "grp_fu_223_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, grp_fu_228_p0, "grp_fu_228_p0");
    sc_trace(mVcdFile, grp_fu_228_p1, "grp_fu_228_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, grp_fu_237_p0, "grp_fu_237_p0");
    sc_trace(mVcdFile, grp_fu_240_p0, "grp_fu_240_p0");
    sc_trace(mVcdFile, grp_fu_240_p1, "grp_fu_240_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state36, "ap_CS_fsm_state36");
    sc_trace(mVcdFile, tmp_49_fu_270_p4, "tmp_49_fu_270_p4");
    sc_trace(mVcdFile, tmp_50_fu_284_p4, "tmp_50_fu_284_p4");
    sc_trace(mVcdFile, i_op_assign_1_cast2_fu_322_p1, "i_op_assign_1_cast2_fu_322_p1");
    sc_trace(mVcdFile, tmp_44_cast_fu_346_p1, "tmp_44_cast_fu_346_p1");
    sc_trace(mVcdFile, in_data2_sum_fu_349_p2, "in_data2_sum_fu_349_p2");
    sc_trace(mVcdFile, i_op_assign_2_cast1_fu_364_p1, "i_op_assign_2_cast1_fu_364_p1");
    sc_trace(mVcdFile, index_fu_379_p2, "index_fu_379_p2");
    sc_trace(mVcdFile, tmp_34_cast_fu_384_p1, "tmp_34_cast_fu_384_p1");
    sc_trace(mVcdFile, out_data4_sum6_fu_388_p2, "out_data4_sum6_fu_388_p2");
    sc_trace(mVcdFile, tmp1_fu_403_p0, "tmp1_fu_403_p0");
    sc_trace(mVcdFile, tmp1_fu_403_p1, "tmp1_fu_403_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, tmp1_fu_403_p10, "tmp1_fu_403_p10");
#endif

    }
    mHdltvinHandle.open("GELU.hdltvin.dat");
    mHdltvoutHandle.open("GELU.hdltvout.dat");
}

GELU::~GELU() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete GELU_AXILiteS_s_axi_U;
    delete GELU_gmem_m_axi_U;
    delete grp_generic_tanh_float_s_fu_212;
    delete GELU_fadd_32ns_32ncg_U24;
    delete GELU_fmul_32ns_32hbi_U25;
    delete GELU_fptrunc_64nsjbC_U26;
    delete GELU_fpext_32ns_6kbM_U27;
    delete GELU_dmul_64ns_64ocq_U28;
    delete GELU_mul_mul_12nspcA_U29;
}

void GELU::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void GELU::thread_ap_var_for_const6() {
    ap_var_for_const6 = ap_const_logic_0;
}

void GELU::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv1_0;
}

void GELU::thread_ap_var_for_const5() {
    ap_var_for_const5 = ap_const_lv32_1;
}

void GELU::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv3_0;
}

void GELU::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv2_0;
}

void GELU::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv4_0;
}

void GELU::thread_ap_var_for_const7() {
    ap_var_for_const7 = ap_const_lv4_F;
}

void GELU::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_gmem_ARREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
            if (esl_seteq<1,1,1>(ap_sig_ioackin_gmem_ARREADY.read(), ap_const_logic_1)) {
                ap_reg_ioackin_gmem_ARREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, gmem_ARREADY.read())) {
                ap_reg_ioackin_gmem_ARREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_gmem_AWREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read())) {
            if (esl_seteq<1,1,1>(ap_sig_ioackin_gmem_AWREADY.read(), ap_const_logic_1)) {
                ap_reg_ioackin_gmem_AWREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, gmem_AWREADY.read())) {
                ap_reg_ioackin_gmem_AWREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_gmem_WREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
            if (esl_seteq<1,1,1>(ap_sig_ioackin_gmem_WREADY.read(), ap_const_logic_1)) {
                ap_reg_ioackin_gmem_WREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, gmem_WREADY.read())) {
                ap_reg_ioackin_gmem_WREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_generic_tanh_float_s_fu_212_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
            grp_generic_tanh_float_s_fu_212_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_generic_tanh_float_s_fu_212_ap_ready.read())) {
            grp_generic_tanh_float_s_fu_212_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         !(esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, gmem_RVALID.read())) && 
         esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_1))) {
        i_op_assign_1_reg_190 = h_reg_461.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_311_p2.read()))) {
        i_op_assign_1_reg_190 = ap_const_lv12_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        i_op_assign_2_reg_201 = ap_const_lv12_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read()) && 
                esl_seteq<1,1,1>(gmem_BVALID.read(), ap_const_logic_1))) {
        i_op_assign_2_reg_201 = w_reg_485.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_326_p2.read(), ap_const_lv1_1))) {
        i_op_assign_reg_167 = d_reg_453.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_op_assign_reg_167 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_326_p2.read(), ap_const_lv1_1))) {
        phi_mul_reg_178 = next_mul_reg_445.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        phi_mul_reg_178 = ap_const_lv20_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        d_reg_453 = d_fu_316_p2.read();
        next_mul_reg_445 = next_mul_fu_306_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, gmem_RVALID.read())))) {
        gmem_addr_1_reg_498 =  (sc_lv<32>) (out_data4_sum6_cast_fu_393_p1.read());
        x_reg_490 = gmem_RDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        gmem_addr_reg_476 =  (sc_lv<32>) (in_data2_sum_cast_fu_354_p1.read());
        tmp1_reg_471 = tmp1_fu_403_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        h_reg_461 = h_fu_331_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        input_depth_V_read_reg_409 = input_depth_V.read();
        input_height_V_read_reg_414 = input_height_V.read();
        input_width_V_read_reg_419 = input_width_V.read();
        tmp_14_cast_reg_424 = tmp_14_cast_fu_280_p1.read();
        tmp_15_cast_reg_429 = tmp_15_cast_fu_294_p1.read();
        tmp_3_reg_434 = tmp_3_fu_298_p1.read();
        tmp_4_cast4_reg_440 = tmp_4_cast4_fu_302_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()))) {
        reg_245 = grp_fu_228_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read()))) {
        reg_252 = grp_fu_223_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()) && 
  esl_seteq<1,1,1>(grp_generic_tanh_float_s_fu_212_ap_done.read(), ap_const_logic_1)) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read()))) {
        reg_258 = grp_fu_237_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read()))) {
        reg_264 = grp_fu_240_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()) && esl_seteq<1,1,1>(grp_generic_tanh_float_s_fu_212_ap_done.read(), ap_const_logic_1))) {
        tanh_val_reg_504 = grp_generic_tanh_float_s_fu_212_ap_return.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) && esl_seteq<1,1,1>(ap_sig_ioackin_gmem_AWREADY.read(), ap_const_logic_1))) {
        tmp_42_reg_509 = tmp_42_fu_234_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_326_p2.read()))) {
        tmp_reg_466 = tmp_fu_337_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && !(esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, gmem_RVALID.read())))) {
        w_reg_485 = w_fu_373_p2.read();
    }
}

void GELU::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void GELU::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void GELU::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void GELU::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void GELU::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void GELU::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void GELU::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void GELU::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void GELU::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void GELU::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void GELU::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void GELU::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void GELU::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void GELU::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void GELU::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read()[28];
}

void GELU::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void GELU::thread_ap_CS_fsm_state30() {
    ap_CS_fsm_state30 = ap_CS_fsm.read()[29];
}

void GELU::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read()[30];
}

void GELU::thread_ap_CS_fsm_state34() {
    ap_CS_fsm_state34 = ap_CS_fsm.read()[33];
}

void GELU::thread_ap_CS_fsm_state35() {
    ap_CS_fsm_state35 = ap_CS_fsm.read()[34];
}

void GELU::thread_ap_CS_fsm_state36() {
    ap_CS_fsm_state36 = ap_CS_fsm.read()[35];
}

void GELU::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void GELU::thread_ap_CS_fsm_state40() {
    ap_CS_fsm_state40 = ap_CS_fsm.read()[39];
}

void GELU::thread_ap_CS_fsm_state41() {
    ap_CS_fsm_state41 = ap_CS_fsm.read()[40];
}

void GELU::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void GELU::thread_ap_CS_fsm_state47() {
    ap_CS_fsm_state47 = ap_CS_fsm.read()[46];
}

void GELU::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void GELU::thread_ap_block_state12() {
    ap_block_state12 = (esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, gmem_RVALID.read()));
}

void GELU::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_311_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void GELU::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void GELU::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_311_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void GELU::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void GELU::thread_ap_sig_ioackin_gmem_ARREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_gmem_ARREADY.read())) {
        ap_sig_ioackin_gmem_ARREADY = gmem_ARREADY.read();
    } else {
        ap_sig_ioackin_gmem_ARREADY = ap_const_logic_1;
    }
}

void GELU::thread_ap_sig_ioackin_gmem_AWREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_gmem_AWREADY.read())) {
        ap_sig_ioackin_gmem_AWREADY = gmem_AWREADY.read();
    } else {
        ap_sig_ioackin_gmem_AWREADY = ap_const_logic_1;
    }
}

void GELU::thread_ap_sig_ioackin_gmem_WREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_gmem_WREADY.read())) {
        ap_sig_ioackin_gmem_WREADY = gmem_WREADY.read();
    } else {
        ap_sig_ioackin_gmem_WREADY = ap_const_logic_1;
    }
}

void GELU::thread_d_fu_316_p2() {
    d_fu_316_p2 = (!i_op_assign_reg_167.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(i_op_assign_reg_167.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void GELU::thread_exitcond1_fu_326_p2() {
    exitcond1_fu_326_p2 = (!i_op_assign_1_reg_190.read().is_01() || !input_height_V_read_reg_414.read().is_01())? sc_lv<1>(): sc_lv<1>(i_op_assign_1_reg_190.read() == input_height_V_read_reg_414.read());
}

void GELU::thread_exitcond2_fu_311_p2() {
    exitcond2_fu_311_p2 = (!i_op_assign_reg_167.read().is_01() || !input_depth_V_read_reg_409.read().is_01())? sc_lv<1>(): sc_lv<1>(i_op_assign_reg_167.read() == input_depth_V_read_reg_409.read());
}

void GELU::thread_exitcond_fu_368_p2() {
    exitcond_fu_368_p2 = (!i_op_assign_2_reg_201.read().is_01() || !input_width_V_read_reg_419.read().is_01())? sc_lv<1>(): sc_lv<1>(i_op_assign_2_reg_201.read() == input_width_V_read_reg_419.read());
}

void GELU::thread_gmem_ARVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_gmem_ARREADY.read()))) {
        gmem_ARVALID = ap_const_logic_1;
    } else {
        gmem_ARVALID = ap_const_logic_0;
    }
}

void GELU::thread_gmem_AWVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_gmem_AWREADY.read()))) {
        gmem_AWVALID = ap_const_logic_1;
    } else {
        gmem_AWVALID = ap_const_logic_0;
    }
}

void GELU::thread_gmem_BREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read()) && 
         esl_seteq<1,1,1>(gmem_BVALID.read(), ap_const_logic_1))) {
        gmem_BREADY = ap_const_logic_1;
    } else {
        gmem_BREADY = ap_const_logic_0;
    }
}

void GELU::thread_gmem_RREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, gmem_RVALID.read())))) {
        gmem_RREADY = ap_const_logic_1;
    } else {
        gmem_RREADY = ap_const_logic_0;
    }
}

void GELU::thread_gmem_WVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_gmem_WREADY.read()))) {
        gmem_WVALID = ap_const_logic_1;
    } else {
        gmem_WVALID = ap_const_logic_0;
    }
}

void GELU::thread_gmem_blk_n_AR() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        gmem_blk_n_AR = m_axi_gmem_ARREADY.read();
    } else {
        gmem_blk_n_AR = ap_const_logic_1;
    }
}

void GELU::thread_gmem_blk_n_AW() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read())) {
        gmem_blk_n_AW = m_axi_gmem_AWREADY.read();
    } else {
        gmem_blk_n_AW = ap_const_logic_1;
    }
}

void GELU::thread_gmem_blk_n_B() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read())) {
        gmem_blk_n_B = m_axi_gmem_BVALID.read();
    } else {
        gmem_blk_n_B = ap_const_logic_1;
    }
}

void GELU::thread_gmem_blk_n_R() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_0))) {
        gmem_blk_n_R = m_axi_gmem_RVALID.read();
    } else {
        gmem_blk_n_R = ap_const_logic_1;
    }
}

void GELU::thread_gmem_blk_n_W() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        gmem_blk_n_W = m_axi_gmem_WREADY.read();
    } else {
        gmem_blk_n_W = ap_const_logic_1;
    }
}

void GELU::thread_grp_fu_223_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        grp_fu_223_p0 = tanh_val_reg_504.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_fu_223_p0 = x_reg_490.read();
    } else {
        grp_fu_223_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void GELU::thread_grp_fu_223_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        grp_fu_223_p1 = ap_const_lv32_3F800000;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        grp_fu_223_p1 = reg_245.read();
    } else {
        grp_fu_223_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void GELU::thread_grp_fu_228_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        grp_fu_228_p0 = reg_252.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        grp_fu_228_p0 = reg_245.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_228_p0 = x_reg_490.read();
    } else {
        grp_fu_228_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void GELU::thread_grp_fu_228_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        grp_fu_228_p1 = ap_const_lv32_3F4C422A;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        grp_fu_228_p1 = ap_const_lv32_3D372713;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        grp_fu_228_p1 = x_reg_490.read();
    } else {
        grp_fu_228_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void GELU::thread_grp_fu_237_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())) {
        grp_fu_237_p0 = reg_252.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read())) {
        grp_fu_237_p0 = x_reg_490.read();
    } else {
        grp_fu_237_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void GELU::thread_grp_fu_240_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read())) {
        grp_fu_240_p0 = reg_264.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        grp_fu_240_p0 = reg_258.read();
    } else {
        grp_fu_240_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void GELU::thread_grp_fu_240_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read())) {
        grp_fu_240_p1 = reg_258.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        grp_fu_240_p1 = ap_const_lv64_3FE0000000000000;
    } else {
        grp_fu_240_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void GELU::thread_grp_generic_tanh_float_s_fu_212_ap_start() {
    grp_generic_tanh_float_s_fu_212_ap_start = grp_generic_tanh_float_s_fu_212_ap_start_reg.read();
}

void GELU::thread_h_fu_331_p2() {
    h_fu_331_p2 = (!i_op_assign_1_reg_190.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(i_op_assign_1_reg_190.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void GELU::thread_i_op_assign_1_cast2_fu_322_p1() {
    i_op_assign_1_cast2_fu_322_p1 = esl_zext<20,12>(i_op_assign_1_reg_190.read());
}

void GELU::thread_i_op_assign_2_cast1_fu_364_p1() {
    i_op_assign_2_cast1_fu_364_p1 = esl_zext<32,12>(i_op_assign_2_reg_201.read());
}

void GELU::thread_in_data2_sum_cast_fu_354_p1() {
    in_data2_sum_cast_fu_354_p1 = esl_sext<64,33>(in_data2_sum_fu_349_p2.read());
}

void GELU::thread_in_data2_sum_fu_349_p2() {
    in_data2_sum_fu_349_p2 = (!tmp_44_cast_fu_346_p1.read().is_01() || !tmp_15_cast_reg_429.read().is_01())? sc_lv<33>(): (sc_bigint<33>(tmp_44_cast_fu_346_p1.read()) + sc_biguint<33>(tmp_15_cast_reg_429.read()));
}

void GELU::thread_index_fu_379_p2() {
    index_fu_379_p2 = (!i_op_assign_2_cast1_fu_364_p1.read().is_01() || !tmp1_reg_471.read().is_01())? sc_lv<32>(): (sc_biguint<32>(i_op_assign_2_cast1_fu_364_p1.read()) + sc_biguint<32>(tmp1_reg_471.read()));
}

void GELU::thread_next_mul_fu_306_p2() {
    next_mul_fu_306_p2 = (!phi_mul_reg_178.read().is_01() || !tmp_4_cast4_reg_440.read().is_01())? sc_lv<20>(): (sc_biguint<20>(phi_mul_reg_178.read()) + sc_biguint<20>(tmp_4_cast4_reg_440.read()));
}

void GELU::thread_out_data4_sum6_cast_fu_393_p1() {
    out_data4_sum6_cast_fu_393_p1 = esl_sext<64,33>(out_data4_sum6_fu_388_p2.read());
}

void GELU::thread_out_data4_sum6_fu_388_p2() {
    out_data4_sum6_fu_388_p2 = (!tmp_34_cast_fu_384_p1.read().is_01() || !tmp_14_cast_reg_424.read().is_01())? sc_lv<33>(): (sc_bigint<33>(tmp_34_cast_fu_384_p1.read()) + sc_biguint<33>(tmp_14_cast_reg_424.read()));
}

void GELU::thread_tmp1_fu_403_p0() {
    tmp1_fu_403_p0 =  (sc_lv<12>) (tmp_3_reg_434.read());
}

void GELU::thread_tmp1_fu_403_p1() {
    tmp1_fu_403_p1 =  (sc_lv<20>) (tmp1_fu_403_p10.read());
}

void GELU::thread_tmp1_fu_403_p10() {
    tmp1_fu_403_p10 = esl_zext<32,20>(tmp_reg_466.read());
}

void GELU::thread_tmp_14_cast_fu_280_p1() {
    tmp_14_cast_fu_280_p1 = esl_zext<33,30>(tmp_49_fu_270_p4.read());
}

void GELU::thread_tmp_15_cast_fu_294_p1() {
    tmp_15_cast_fu_294_p1 = esl_zext<33,30>(tmp_50_fu_284_p4.read());
}

void GELU::thread_tmp_34_cast_fu_384_p1() {
    tmp_34_cast_fu_384_p1 = esl_sext<33,32>(index_fu_379_p2.read());
}

void GELU::thread_tmp_3_fu_298_p1() {
    tmp_3_fu_298_p1 = esl_zext<32,12>(input_width_V.read());
}

void GELU::thread_tmp_44_cast_fu_346_p1() {
    tmp_44_cast_fu_346_p1 = esl_sext<33,32>(tmp1_fu_403_p2.read());
}

void GELU::thread_tmp_49_fu_270_p4() {
    tmp_49_fu_270_p4 = out_data.read().range(31, 2);
}

void GELU::thread_tmp_4_cast4_fu_302_p1() {
    tmp_4_cast4_fu_302_p1 = esl_zext<20,12>(input_height_V.read());
}

void GELU::thread_tmp_50_fu_284_p4() {
    tmp_50_fu_284_p4 = in_data.read().range(31, 2);
}

void GELU::thread_tmp_fu_337_p2() {
    tmp_fu_337_p2 = (!i_op_assign_1_cast2_fu_322_p1.read().is_01() || !phi_mul_reg_178.read().is_01())? sc_lv<20>(): (sc_biguint<20>(i_op_assign_1_cast2_fu_322_p1.read()) + sc_biguint<20>(phi_mul_reg_178.read()));
}

void GELU::thread_w_fu_373_p2() {
    w_fu_373_p2 = (!i_op_assign_2_reg_201.read().is_01() || !ap_const_lv12_1.is_01())? sc_lv<12>(): (sc_biguint<12>(i_op_assign_2_reg_201.read()) + sc_biguint<12>(ap_const_lv12_1));
}

void GELU::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_311_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond1_fu_326_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_sig_ioackin_gmem_ARREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && !(esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, gmem_RVALID.read())) && esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(exitcond_fu_368_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, gmem_RVALID.read())))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()) && esl_seteq<1,1,1>(grp_generic_tanh_float_s_fu_212_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state31;
            } else {
                ap_NS_fsm = ap_ST_fsm_state30;
            }
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state41;
            break;
        case 1099511627776 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()) && esl_seteq<1,1,1>(ap_sig_ioackin_gmem_AWREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state42;
            } else {
                ap_NS_fsm = ap_ST_fsm_state41;
            }
            break;
        case 2199023255552 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()) && esl_seteq<1,1,1>(ap_sig_ioackin_gmem_WREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state43;
            } else {
                ap_NS_fsm = ap_ST_fsm_state42;
            }
            break;
        case 4398046511104 : 
            ap_NS_fsm = ap_ST_fsm_state44;
            break;
        case 8796093022208 : 
            ap_NS_fsm = ap_ST_fsm_state45;
            break;
        case 17592186044416 : 
            ap_NS_fsm = ap_ST_fsm_state46;
            break;
        case 35184372088832 : 
            ap_NS_fsm = ap_ST_fsm_state47;
            break;
        case 70368744177664 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read()) && esl_seteq<1,1,1>(gmem_BVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state47;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<47>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void GELU::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"m_axi_gmem_AWVALID\" :  \"" << m_axi_gmem_AWVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_AWREADY\" :  \"" << m_axi_gmem_AWREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWADDR\" :  \"" << m_axi_gmem_AWADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWID\" :  \"" << m_axi_gmem_AWID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWLEN\" :  \"" << m_axi_gmem_AWLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWSIZE\" :  \"" << m_axi_gmem_AWSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWBURST\" :  \"" << m_axi_gmem_AWBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWLOCK\" :  \"" << m_axi_gmem_AWLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWCACHE\" :  \"" << m_axi_gmem_AWCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWPROT\" :  \"" << m_axi_gmem_AWPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWQOS\" :  \"" << m_axi_gmem_AWQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWREGION\" :  \"" << m_axi_gmem_AWREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWUSER\" :  \"" << m_axi_gmem_AWUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_WVALID\" :  \"" << m_axi_gmem_WVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_WREADY\" :  \"" << m_axi_gmem_WREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_WDATA\" :  \"" << m_axi_gmem_WDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_WSTRB\" :  \"" << m_axi_gmem_WSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_WLAST\" :  \"" << m_axi_gmem_WLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_WID\" :  \"" << m_axi_gmem_WID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_WUSER\" :  \"" << m_axi_gmem_WUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARVALID\" :  \"" << m_axi_gmem_ARVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_ARREADY\" :  \"" << m_axi_gmem_ARREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARADDR\" :  \"" << m_axi_gmem_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARID\" :  \"" << m_axi_gmem_ARID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARLEN\" :  \"" << m_axi_gmem_ARLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARSIZE\" :  \"" << m_axi_gmem_ARSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARBURST\" :  \"" << m_axi_gmem_ARBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARLOCK\" :  \"" << m_axi_gmem_ARLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARCACHE\" :  \"" << m_axi_gmem_ARCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARPROT\" :  \"" << m_axi_gmem_ARPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARQOS\" :  \"" << m_axi_gmem_ARQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARREGION\" :  \"" << m_axi_gmem_ARREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARUSER\" :  \"" << m_axi_gmem_ARUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_RVALID\" :  \"" << m_axi_gmem_RVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_RREADY\" :  \"" << m_axi_gmem_RREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_RDATA\" :  \"" << m_axi_gmem_RDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_RLAST\" :  \"" << m_axi_gmem_RLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_RID\" :  \"" << m_axi_gmem_RID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_RUSER\" :  \"" << m_axi_gmem_RUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_RRESP\" :  \"" << m_axi_gmem_RRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_BVALID\" :  \"" << m_axi_gmem_BVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_BREADY\" :  \"" << m_axi_gmem_BREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_BRESP\" :  \"" << m_axi_gmem_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_BID\" :  \"" << m_axi_gmem_BID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_BUSER\" :  \"" << m_axi_gmem_BUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

