// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="LeakyReLU,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=7,HLS_SYN_FF=1542,HLS_SYN_LUT=1726,HLS_VERSION=2018_3}" *)

module LeakyReLU (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_state11 = 28'd1024;
parameter    ap_ST_fsm_state12 = 28'd2048;
parameter    ap_ST_fsm_state13 = 28'd4096;
parameter    ap_ST_fsm_state14 = 28'd8192;
parameter    ap_ST_fsm_state15 = 28'd16384;
parameter    ap_ST_fsm_state16 = 28'd32768;
parameter    ap_ST_fsm_state17 = 28'd65536;
parameter    ap_ST_fsm_state18 = 28'd131072;
parameter    ap_ST_fsm_state19 = 28'd262144;
parameter    ap_ST_fsm_state20 = 28'd524288;
parameter    ap_ST_fsm_state21 = 28'd1048576;
parameter    ap_ST_fsm_state22 = 28'd2097152;
parameter    ap_ST_fsm_state23 = 28'd4194304;
parameter    ap_ST_fsm_state24 = 28'd8388608;
parameter    ap_ST_fsm_state25 = 28'd16777216;
parameter    ap_ST_fsm_state26 = 28'd33554432;
parameter    ap_ST_fsm_state27 = 28'd67108864;
parameter    ap_ST_fsm_state28 = 28'd134217728;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [11:0] channel_V;
wire   [11:0] height_V;
wire   [11:0] width_V;
wire   [31:0] in_data;
wire   [31:0] out_data;
wire   [31:0] alpha;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state22;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state23;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state21;
reg   [0:0] tmp_2_reg_581;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state12;
wire   [0:0] exitcond_fu_352_p2;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state5;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg   [31:0] gmem_AWADDR;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg   [31:0] gmem_WDATA;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
reg    gmem_BREADY;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg   [31:0] alpha_read_reg_465;
reg   [11:0] width_V_read_reg_470;
reg   [11:0] height_V_read_reg_475;
wire   [36:0] tmp_cast_fu_248_p1;
reg   [36:0] tmp_cast_reg_480;
wire   [36:0] tmp_1_cast_fu_262_p1;
reg   [36:0] tmp_1_cast_reg_485;
wire   [23:0] rhs_V_cast_fu_266_p1;
reg   [23:0] rhs_V_cast_reg_490;
wire   [35:0] rhs_V_1_cast_fu_270_p1;
reg   [35:0] rhs_V_1_cast_reg_495;
wire   [23:0] rhs_V_2_cast_fu_274_p1;
reg   [23:0] rhs_V_2_cast_reg_500;
wire   [31:0] tmp_5_fu_278_p1;
reg   [31:0] tmp_5_reg_505;
wire   [23:0] bound_fu_442_p2;
reg   [23:0] bound_reg_510;
wire   [23:0] indvar_flatten_next_fu_291_p2;
reg   [23:0] indvar_flatten_next_reg_518;
wire    ap_CS_fsm_state2;
wire   [11:0] i_op_assign_1_mid2_fu_302_p3;
reg   [11:0] i_op_assign_1_mid2_reg_523;
wire   [0:0] exitcond_flatten_fu_286_p2;
wire   [11:0] ret_V_1_mid2_v_v_v_v_fu_316_p3;
reg   [11:0] ret_V_1_mid2_v_v_v_v_reg_529;
wire   [23:0] ret_V_1_mid2_v_v_fu_448_p2;
reg   [23:0] ret_V_1_mid2_v_v_reg_534;
wire   [35:0] ret_V_1_mid2_fu_453_p2;
reg   [35:0] ret_V_1_mid2_reg_539;
wire    ap_CS_fsm_state3;
wire   [35:0] grp_fu_458_p3;
reg   [35:0] ret_V_1_reg_544;
wire    ap_CS_fsm_state4;
reg   [31:0] gmem_addr_reg_549;
wire   [11:0] w_fu_357_p2;
reg   [11:0] w_reg_558;
reg    ap_block_state12;
(* use_dsp48 = "no" *) wire   [35:0] ret_V_2_fu_367_p2;
reg   [35:0] ret_V_2_reg_563;
reg   [31:0] gmem_addr_read_reg_568;
wire   [11:0] h_fu_372_p2;
wire   [0:0] tmp_2_fu_416_p2;
wire    ap_CS_fsm_state13;
reg   [31:0] gmem_addr_2_reg_585;
reg   [31:0] gmem_addr_1_reg_591;
wire   [31:0] grp_fu_225_p2;
reg   [31:0] tmp_6_reg_597;
reg    ap_sig_ioackin_gmem_AWREADY;
reg   [23:0] indvar_flatten_reg_181;
reg   [11:0] i_op_assign_reg_192;
reg   [11:0] i_op_assign_1_reg_203;
reg   [11:0] i_op_assign_2_reg_214;
reg    ap_block_state21;
wire    ap_CS_fsm_state11;
wire   [63:0] in_data2_sum_cast_fu_342_p1;
wire   [63:0] out_data4_sum_cast_fu_422_p1;
wire   [63:0] out_data4_sum6_cast_fu_432_p1;
reg    ap_reg_ioackin_gmem_ARREADY;
reg    ap_sig_ioackin_gmem_ARREADY;
reg    ap_reg_ioackin_gmem_AWREADY;
reg    ap_reg_ioackin_gmem_WREADY;
reg    ap_sig_ioackin_gmem_WREADY;
wire   [36:0] tmp_4_cast_fu_377_p1;
wire   [29:0] tmp_fu_238_p4;
wire   [29:0] tmp_1_fu_252_p4;
wire   [0:0] exitcond1_fu_297_p2;
wire   [11:0] c7_fu_310_p2;
wire   [36:0] tmp_3_cast_fu_334_p1;
wire   [36:0] in_data2_sum_fu_337_p2;
wire   [35:0] rhs_V_4_cast_fu_363_p1;
wire   [31:0] in_data_load_to_int_fu_381_p1;
wire   [7:0] tmp_7_fu_384_p4;
wire   [22:0] tmp_3_fu_394_p1;
wire   [0:0] notrhs_fu_404_p2;
wire   [0:0] notlhs_fu_398_p2;
wire   [0:0] tmp_9_fu_410_p2;
wire   [0:0] tmp_s_fu_229_p2;
wire   [36:0] grp_fu_234_p2;
wire   [11:0] bound_fu_442_p0;
wire   [11:0] bound_fu_442_p1;
wire   [11:0] ret_V_1_mid2_v_v_fu_448_p0;
wire   [11:0] ret_V_1_mid2_v_v_fu_448_p1;
wire   [11:0] ret_V_1_mid2_fu_453_p0;
wire   [23:0] ret_V_1_mid2_fu_453_p1;
wire   [11:0] grp_fu_458_p0;
wire   [11:0] grp_fu_458_p1;
reg    grp_fu_225_ce;
wire    ap_CS_fsm_state14;
reg   [27:0] ap_NS_fsm;
wire   [23:0] bound_fu_442_p00;
wire   [23:0] bound_fu_442_p10;
wire   [23:0] grp_fu_458_p10;
wire   [35:0] ret_V_1_mid2_fu_453_p10;
wire   [23:0] ret_V_1_mid2_v_v_fu_448_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 28'd1;
#0 ap_reg_ioackin_gmem_ARREADY = 1'b0;
#0 ap_reg_ioackin_gmem_AWREADY = 1'b0;
#0 ap_reg_ioackin_gmem_WREADY = 1'b0;
end

LeakyReLU_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
LeakyReLU_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .channel_V(channel_V),
    .height_V(height_V),
    .width_V(width_V),
    .in_data(in_data),
    .out_data(out_data),
    .alpha(alpha)
);

LeakyReLU_gmem_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
LeakyReLU_gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_addr_reg_549),
    .I_ARID(1'd0),
    .I_ARLEN(tmp_5_reg_505),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_AWADDR),
    .I_AWID(1'd0),
    .I_AWLEN(32'd1),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(gmem_WDATA),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

LeakyReLU_fmul_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
LeakyReLU_fmul_32bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(gmem_addr_read_reg_568),
    .din1(alpha_read_reg_465),
    .ce(grp_fu_225_ce),
    .dout(grp_fu_225_p2)
);

LeakyReLU_fcmp_32cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
LeakyReLU_fcmp_32cud_U2(
    .din0(gmem_addr_read_reg_568),
    .din1(32'd0),
    .opcode(5'd2),
    .dout(tmp_s_fu_229_p2)
);

LeakyReLU_mul_muldEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 24 ))
LeakyReLU_mul_muldEe_U3(
    .din0(bound_fu_442_p0),
    .din1(bound_fu_442_p1),
    .dout(bound_fu_442_p2)
);

LeakyReLU_mul_muldEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 24 ))
LeakyReLU_mul_muldEe_U4(
    .din0(ret_V_1_mid2_v_v_fu_448_p0),
    .din1(ret_V_1_mid2_v_v_fu_448_p1),
    .dout(ret_V_1_mid2_v_v_fu_448_p2)
);

LeakyReLU_mul_muleOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 36 ))
LeakyReLU_mul_muleOg_U5(
    .din0(ret_V_1_mid2_fu_453_p0),
    .din1(ret_V_1_mid2_fu_453_p1),
    .dout(ret_V_1_mid2_fu_453_p2)
);

LeakyReLU_mac_mulfYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
LeakyReLU_mac_mulfYi_U6(
    .din0(grp_fu_458_p0),
    .din1(grp_fu_458_p1),
    .din2(ret_V_1_mid2_reg_539),
    .dout(grp_fu_458_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_ARREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            if ((ap_sig_ioackin_gmem_ARREADY == 1'b1)) begin
                ap_reg_ioackin_gmem_ARREADY <= 1'b0;
            end else if ((gmem_ARREADY == 1'b1)) begin
                ap_reg_ioackin_gmem_ARREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_AWREADY <= 1'b0;
    end else begin
        if ((((ap_sig_ioackin_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | ((ap_sig_ioackin_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state22)))) begin
            ap_reg_ioackin_gmem_AWREADY <= 1'b0;
        end else if ((((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | ((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state22)))) begin
            ap_reg_ioackin_gmem_AWREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_WREADY <= 1'b0;
    end else begin
        if ((((ap_sig_ioackin_gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((ap_sig_ioackin_gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state23)))) begin
            ap_reg_ioackin_gmem_WREADY <= 1'b0;
        end else if ((((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state23)))) begin
            ap_reg_ioackin_gmem_WREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((gmem_RVALID == 1'b0) & (exitcond_fu_352_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state12) & (exitcond_fu_352_p2 == 1'd1))) begin
        i_op_assign_1_reg_203 <= h_fu_372_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_op_assign_1_reg_203 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        i_op_assign_2_reg_214 <= 12'd0;
    end else if ((~((gmem_BVALID == 1'b0) & (tmp_2_reg_581 == 1'd0)) & (1'b1 == ap_CS_fsm_state21))) begin
        i_op_assign_2_reg_214 <= w_reg_558;
    end
end

always @ (posedge ap_clk) begin
    if ((~((gmem_RVALID == 1'b0) & (exitcond_fu_352_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state12) & (exitcond_fu_352_p2 == 1'd1))) begin
        i_op_assign_reg_192 <= ret_V_1_mid2_v_v_v_v_reg_529;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_op_assign_reg_192 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((gmem_RVALID == 1'b0) & (exitcond_fu_352_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state12) & (exitcond_fu_352_p2 == 1'd1))) begin
        indvar_flatten_reg_181 <= indvar_flatten_next_reg_518;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_181 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        alpha_read_reg_465 <= alpha;
        bound_reg_510 <= bound_fu_442_p2;
        height_V_read_reg_475 <= height_V;
        rhs_V_1_cast_reg_495[11 : 0] <= rhs_V_1_cast_fu_270_p1[11 : 0];
        rhs_V_2_cast_reg_500[11 : 0] <= rhs_V_2_cast_fu_274_p1[11 : 0];
        rhs_V_cast_reg_490[11 : 0] <= rhs_V_cast_fu_266_p1[11 : 0];
        tmp_1_cast_reg_485[29 : 0] <= tmp_1_cast_fu_262_p1[29 : 0];
        tmp_5_reg_505[11 : 0] <= tmp_5_fu_278_p1[11 : 0];
        tmp_cast_reg_480[29 : 0] <= tmp_cast_fu_248_p1[29 : 0];
        width_V_read_reg_470 <= width_V;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_fu_416_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        gmem_addr_1_reg_591 <= out_data4_sum6_cast_fu_432_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (tmp_2_fu_416_p2 == 1'd0))) begin
        gmem_addr_2_reg_585 <= out_data4_sum_cast_fu_422_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((gmem_RVALID == 1'b0) & (exitcond_fu_352_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state12) & (exitcond_fu_352_p2 == 1'd0))) begin
        gmem_addr_read_reg_568 <= gmem_RDATA;
        ret_V_2_reg_563 <= ret_V_2_fu_367_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gmem_addr_reg_549 <= in_data2_sum_cast_fu_342_p1;
        ret_V_1_reg_544 <= grp_fu_458_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_flatten_fu_286_p2 == 1'd0))) begin
        i_op_assign_1_mid2_reg_523 <= i_op_assign_1_mid2_fu_302_p3;
        ret_V_1_mid2_v_v_reg_534 <= ret_V_1_mid2_v_v_fu_448_p2;
        ret_V_1_mid2_v_v_v_v_reg_529 <= ret_V_1_mid2_v_v_v_v_fu_316_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        indvar_flatten_next_reg_518 <= indvar_flatten_next_fu_291_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ret_V_1_mid2_reg_539 <= ret_V_1_mid2_fu_453_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_2_reg_581 <= tmp_2_fu_416_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sig_ioackin_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        tmp_6_reg_597 <= grp_fu_225_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((gmem_RVALID == 1'b0) & (exitcond_fu_352_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state12))) begin
        w_reg_558 <= w_fu_357_p2;
    end
end

always @ (*) begin
    if (((exitcond_flatten_fu_286_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten_fu_286_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_ARREADY == 1'b0)) begin
        ap_sig_ioackin_gmem_ARREADY = gmem_ARREADY;
    end else begin
        ap_sig_ioackin_gmem_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_AWREADY == 1'b0)) begin
        ap_sig_ioackin_gmem_AWREADY = gmem_AWREADY;
    end else begin
        ap_sig_ioackin_gmem_AWREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_WREADY == 1'b0)) begin
        ap_sig_ioackin_gmem_WREADY = gmem_WREADY;
    end else begin
        ap_sig_ioackin_gmem_WREADY = 1'b1;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_gmem_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
        gmem_ARVALID = 1'b1;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_AWREADY == 1'b0)) begin
        if ((1'b1 == ap_CS_fsm_state22)) begin
            gmem_AWADDR = gmem_addr_1_reg_591;
        end else if ((1'b1 == ap_CS_fsm_state15)) begin
            gmem_AWADDR = gmem_addr_2_reg_585;
        end else begin
            gmem_AWADDR = 'bx;
        end
    end else begin
        gmem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_reg_ioackin_gmem_AWREADY == 1'b0) & (1'b1 == ap_CS_fsm_state15)) | ((ap_reg_ioackin_gmem_AWREADY == 1'b0) & (1'b1 == ap_CS_fsm_state22)))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((~((gmem_BVALID == 1'b0) & (tmp_2_reg_581 == 1'd0)) & (1'b1 == ap_CS_fsm_state21) & (tmp_2_reg_581 == 1'd0)) | ((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state28)))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((gmem_RVALID == 1'b0) & (exitcond_fu_352_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state12) & (exitcond_fu_352_p2 == 1'd0))) begin
        gmem_RREADY = 1'b1;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_WREADY == 1'b0)) begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            gmem_WDATA = gmem_addr_read_reg_568;
        end else if ((1'b1 == ap_CS_fsm_state16)) begin
            gmem_WDATA = tmp_6_reg_597;
        end else begin
            gmem_WDATA = 'bx;
        end
    end else begin
        gmem_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_reg_ioackin_gmem_WREADY == 1'b0) & (1'b1 == ap_CS_fsm_state16)) | ((ap_reg_ioackin_gmem_WREADY == 1'b0) & (1'b1 == ap_CS_fsm_state23)))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state22))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | ((1'b1 == ap_CS_fsm_state21) & (tmp_2_reg_581 == 1'd0)))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (exitcond_fu_352_p2 == 1'd0))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state23))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | ((ap_sig_ioackin_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15)))) begin
        grp_fu_225_ce = 1'b1;
    end else begin
        grp_fu_225_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond_flatten_fu_286_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((ap_sig_ioackin_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if ((~((gmem_RVALID == 1'b0) & (exitcond_fu_352_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state12) & (exitcond_fu_352_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((gmem_RVALID == 1'b0) & (exitcond_fu_352_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state12) & (exitcond_fu_352_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((tmp_2_fu_416_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((ap_sig_ioackin_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((ap_sig_ioackin_gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if ((~((gmem_BVALID == 1'b0) & (tmp_2_reg_581 == 1'd0)) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((ap_sig_ioackin_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((ap_sig_ioackin_gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state12 = ((gmem_RVALID == 1'b0) & (exitcond_fu_352_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state21 = ((gmem_BVALID == 1'b0) & (tmp_2_reg_581 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bound_fu_442_p0 = bound_fu_442_p00;

assign bound_fu_442_p00 = height_V;

assign bound_fu_442_p1 = bound_fu_442_p10;

assign bound_fu_442_p10 = channel_V;

assign c7_fu_310_p2 = (i_op_assign_reg_192 + 12'd1);

assign exitcond1_fu_297_p2 = ((i_op_assign_1_reg_203 == height_V_read_reg_475) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_286_p2 = ((indvar_flatten_reg_181 == bound_reg_510) ? 1'b1 : 1'b0);

assign exitcond_fu_352_p2 = ((i_op_assign_2_reg_214 == width_V_read_reg_470) ? 1'b1 : 1'b0);

assign grp_fu_234_p2 = (tmp_cast_reg_480 + tmp_4_cast_fu_377_p1);

assign grp_fu_458_p0 = rhs_V_2_cast_reg_500;

assign grp_fu_458_p1 = grp_fu_458_p10;

assign grp_fu_458_p10 = i_op_assign_1_mid2_reg_523;

assign h_fu_372_p2 = (i_op_assign_1_mid2_reg_523 + 12'd1);

assign i_op_assign_1_mid2_fu_302_p3 = ((exitcond1_fu_297_p2[0:0] === 1'b1) ? 12'd0 : i_op_assign_1_reg_203);

assign in_data2_sum_cast_fu_342_p1 = in_data2_sum_fu_337_p2;

assign in_data2_sum_fu_337_p2 = (tmp_3_cast_fu_334_p1 + tmp_1_cast_reg_485);

assign in_data_load_to_int_fu_381_p1 = gmem_addr_read_reg_568;

assign indvar_flatten_next_fu_291_p2 = (indvar_flatten_reg_181 + 24'd1);

assign notlhs_fu_398_p2 = ((tmp_7_fu_384_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs_fu_404_p2 = ((tmp_3_fu_394_p1 == 23'd0) ? 1'b1 : 1'b0);

assign out_data4_sum6_cast_fu_432_p1 = grp_fu_234_p2;

assign out_data4_sum_cast_fu_422_p1 = grp_fu_234_p2;

assign ret_V_1_mid2_fu_453_p0 = rhs_V_1_cast_reg_495;

assign ret_V_1_mid2_fu_453_p1 = ret_V_1_mid2_fu_453_p10;

assign ret_V_1_mid2_fu_453_p10 = ret_V_1_mid2_v_v_reg_534;

assign ret_V_1_mid2_v_v_fu_448_p0 = rhs_V_cast_reg_490;

assign ret_V_1_mid2_v_v_fu_448_p1 = ret_V_1_mid2_v_v_fu_448_p10;

assign ret_V_1_mid2_v_v_fu_448_p10 = ret_V_1_mid2_v_v_v_v_fu_316_p3;

assign ret_V_1_mid2_v_v_v_v_fu_316_p3 = ((exitcond1_fu_297_p2[0:0] === 1'b1) ? c7_fu_310_p2 : i_op_assign_reg_192);

assign ret_V_2_fu_367_p2 = (rhs_V_4_cast_fu_363_p1 + ret_V_1_reg_544);

assign rhs_V_1_cast_fu_270_p1 = width_V;

assign rhs_V_2_cast_fu_274_p1 = width_V;

assign rhs_V_4_cast_fu_363_p1 = i_op_assign_2_reg_214;

assign rhs_V_cast_fu_266_p1 = height_V;

assign tmp_1_cast_fu_262_p1 = tmp_1_fu_252_p4;

assign tmp_1_fu_252_p4 = {{in_data[31:2]}};

assign tmp_2_fu_416_p2 = (tmp_s_fu_229_p2 & tmp_9_fu_410_p2);

assign tmp_3_cast_fu_334_p1 = grp_fu_458_p3;

assign tmp_3_fu_394_p1 = in_data_load_to_int_fu_381_p1[22:0];

assign tmp_4_cast_fu_377_p1 = ret_V_2_reg_563;

assign tmp_5_fu_278_p1 = width_V;

assign tmp_7_fu_384_p4 = {{in_data_load_to_int_fu_381_p1[30:23]}};

assign tmp_9_fu_410_p2 = (notrhs_fu_404_p2 | notlhs_fu_398_p2);

assign tmp_cast_fu_248_p1 = tmp_fu_238_p4;

assign tmp_fu_238_p4 = {{out_data[31:2]}};

assign w_fu_357_p2 = (i_op_assign_2_reg_214 + 12'd1);

always @ (posedge ap_clk) begin
    tmp_cast_reg_480[36:30] <= 7'b0000000;
    tmp_1_cast_reg_485[36:30] <= 7'b0000000;
    rhs_V_cast_reg_490[23:12] <= 12'b000000000000;
    rhs_V_1_cast_reg_495[35:12] <= 24'b000000000000000000000000;
    rhs_V_2_cast_reg_500[23:12] <= 12'b000000000000;
    tmp_5_reg_505[31:12] <= 20'b00000000000000000000;
end

endmodule //LeakyReLU
