// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _generic_tanh_float_s_HH_
#define _generic_tanh_float_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "exp_generic_double_s.h"
#include "GELU_faddfsub_32ng8j.h"
#include "GELU_fmul_32ns_32hbi.h"
#include "GELU_fdiv_32ns_32ibs.h"
#include "GELU_fptrunc_64nsjbC.h"
#include "GELU_fpext_32ns_6kbM.h"
#include "GELU_fcmp_32ns_32lbW.h"
#include "GELU_dadd_64ns_64mb6.h"

namespace ap_rtl {

struct generic_tanh_float_s : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > t_in;
    sc_out< sc_lv<32> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<32> > ap_var_for_const1;
    sc_signal< sc_lv<64> > ap_var_for_const3;
    sc_signal< sc_lv<5> > ap_var_for_const2;


    // Module declarations
    generic_tanh_float_s(sc_module_name name);
    SC_HAS_PROCESS(generic_tanh_float_s);

    ~generic_tanh_float_s();

    sc_trace_file* mVcdFile;

    exp_generic_double_s* grp_exp_generic_double_s_fu_89;
    GELU_faddfsub_32ng8j<1,4,32,32,32>* GELU_faddfsub_32ng8j_U9;
    GELU_fmul_32ns_32hbi<1,3,32,32,32>* GELU_fmul_32ns_32hbi_U10;
    GELU_fdiv_32ns_32ibs<1,12,32,32,32>* GELU_fdiv_32ns_32ibs_U11;
    GELU_fptrunc_64nsjbC<1,1,64,32>* GELU_fptrunc_64nsjbC_U12;
    GELU_fpext_32ns_6kbM<1,1,32,64>* GELU_fpext_32ns_6kbM_U13;
    GELU_fcmp_32ns_32lbW<1,1,32,32,1>* GELU_fcmp_32ns_32lbW_U14;
    GELU_dadd_64ns_64mb6<1,5,64,64,64>* GELU_dadd_64ns_64mb6_U15;
    sc_signal< sc_lv<68> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > grp_fu_100_p2;
    sc_signal< sc_lv<32> > reg_143;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > tmp_3_reg_348;
    sc_signal< sc_logic > ap_CS_fsm_state29;
    sc_signal< sc_logic > ap_CS_fsm_state45;
    sc_signal< sc_logic > ap_CS_fsm_state64;
    sc_signal< sc_lv<32> > grp_fu_112_p2;
    sc_signal< sc_lv<32> > reg_150;
    sc_signal< sc_logic > ap_CS_fsm_state41;
    sc_signal< sc_logic > ap_CS_fsm_state61;
    sc_signal< sc_lv<1> > p_Result_s_reg_320;
    sc_signal< sc_lv<32> > abst_in_fu_196_p1;
    sc_signal< sc_lv<32> > abst_in_reg_325;
    sc_signal< sc_lv<1> > tmp_fu_202_p2;
    sc_signal< sc_lv<1> > tmp_reg_332;
    sc_signal< sc_lv<1> > tmp_7_fu_208_p2;
    sc_signal< sc_lv<1> > tmp_7_reg_336;
    sc_signal< sc_lv<1> > or_cond_fu_220_p2;
    sc_signal< sc_lv<1> > or_cond_reg_340;
    sc_signal< sc_lv<1> > tmp_1_fu_123_p2;
    sc_signal< sc_lv<1> > tmp_1_reg_344;
    sc_signal< sc_lv<1> > tmp_3_fu_226_p2;
    sc_signal< sc_lv<32> > tmp_4_neg_fu_232_p2;
    sc_signal< sc_lv<32> > tmp_4_neg_reg_353;
    sc_signal< sc_lv<32> > p_1_fu_238_p3;
    sc_signal< sc_lv<32> > tmp_4_fu_246_p1;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > x_2_fu_250_p3;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > xd_fu_120_p1;
    sc_signal< sc_lv<64> > xd_reg_379;
    sc_signal< sc_lv<1> > tmp_i_fu_272_p2;
    sc_signal< sc_lv<1> > tmp_i_30_fu_278_p2;
    sc_signal< sc_lv<64> > grp_exp_generic_double_s_fu_89_ap_return;
    sc_signal< sc_lv<64> > tmp_13_i_reg_384;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_lv<64> > grp_fu_128_p2;
    sc_signal< sc_lv<64> > tmp_14_i_reg_389;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<32> > tmp_15_i_fu_117_p1;
    sc_signal< sc_logic > ap_CS_fsm_state25;
    sc_signal< sc_lv<32> > tmp_8_reg_399;
    sc_signal< sc_logic > ap_CS_fsm_state49;
    sc_signal< sc_lv<32> > tmp_5_fu_315_p1;
    sc_signal< sc_logic > ap_CS_fsm_state50;
    sc_signal< sc_lv<32> > grp_fu_108_p2;
    sc_signal< sc_lv<32> > resultf_reg_409;
    sc_signal< sc_logic > ap_CS_fsm_state67;
    sc_signal< sc_logic > grp_exp_generic_double_s_fu_89_ap_start;
    sc_signal< sc_logic > grp_exp_generic_double_s_fu_89_ap_done;
    sc_signal< sc_logic > grp_exp_generic_double_s_fu_89_ap_idle;
    sc_signal< sc_logic > grp_exp_generic_double_s_fu_89_ap_ready;
    sc_signal< sc_lv<32> > expx_reg_58;
    sc_signal< sc_lv<32> > ap_phi_mux_resultf_4_phi_fu_76_p10;
    sc_signal< sc_lv<32> > resultf_4_reg_72;
    sc_signal< sc_logic > ap_CS_fsm_state68;
    sc_signal< sc_logic > ap_CS_fsm_state46;
    sc_signal< sc_logic > grp_exp_generic_double_s_fu_89_ap_start_reg;
    sc_signal< sc_lv<68> > ap_NS_fsm;
    sc_signal< sc_logic > ap_NS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<32> > grp_fu_100_p0;
    sc_signal< sc_lv<32> > grp_fu_100_p1;
    sc_signal< sc_logic > ap_CS_fsm_state26;
    sc_signal< sc_logic > ap_CS_fsm_state42;
    sc_signal< sc_logic > ap_CS_fsm_state65;
    sc_signal< sc_lv<32> > grp_fu_112_p0;
    sc_signal< sc_lv<32> > grp_fu_112_p1;
    sc_signal< sc_logic > ap_CS_fsm_state30;
    sc_signal< sc_lv<32> > tmp_1_fu_123_p0;
    sc_signal< sc_logic > ap_CS_fsm_state20;
    sc_signal< sc_lv<23> > tmp_V_1_fu_178_p1;
    sc_signal< sc_lv<32> > p_Val2_s_fu_156_p1;
    sc_signal< sc_lv<31> > tmp_15_fu_184_p1;
    sc_signal< sc_lv<32> > p_Result_9_fu_188_p3;
    sc_signal< sc_lv<8> > tmp_V_fu_168_p4;
    sc_signal< sc_lv<1> > tmp_9_fu_214_p2;
    sc_signal< sc_lv<1> > tmp_s_fu_133_p2;
    sc_signal< sc_lv<1> > tmp_6_fu_138_p2;
    sc_signal< sc_lv<32> > p_Val2_3_fu_258_p1;
    sc_signal< sc_lv<8> > tmp_V_2_fu_262_p4;
    sc_signal< sc_lv<32> > tmp_12_to_int_fu_284_p1;
    sc_signal< sc_lv<32> > tmp_12_neg_fu_288_p2;
    sc_signal< sc_lv<32> > tmp_12_fu_294_p1;
    sc_signal< sc_lv<32> > tmp_5_to_int_fu_305_p1;
    sc_signal< sc_lv<32> > tmp_5_neg_fu_309_p2;
    sc_signal< sc_lv<2> > grp_fu_100_opcode;
    sc_signal< sc_lv<32> > p_s_fu_298_p3;
    sc_signal< sc_lv<32> > ap_return_preg;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<68> ap_ST_fsm_state1;
    static const sc_lv<68> ap_ST_fsm_state2;
    static const sc_lv<68> ap_ST_fsm_state3;
    static const sc_lv<68> ap_ST_fsm_state4;
    static const sc_lv<68> ap_ST_fsm_state5;
    static const sc_lv<68> ap_ST_fsm_state6;
    static const sc_lv<68> ap_ST_fsm_state7;
    static const sc_lv<68> ap_ST_fsm_state8;
    static const sc_lv<68> ap_ST_fsm_state9;
    static const sc_lv<68> ap_ST_fsm_state10;
    static const sc_lv<68> ap_ST_fsm_state11;
    static const sc_lv<68> ap_ST_fsm_state12;
    static const sc_lv<68> ap_ST_fsm_state13;
    static const sc_lv<68> ap_ST_fsm_state14;
    static const sc_lv<68> ap_ST_fsm_state15;
    static const sc_lv<68> ap_ST_fsm_state16;
    static const sc_lv<68> ap_ST_fsm_state17;
    static const sc_lv<68> ap_ST_fsm_state18;
    static const sc_lv<68> ap_ST_fsm_state19;
    static const sc_lv<68> ap_ST_fsm_state20;
    static const sc_lv<68> ap_ST_fsm_state21;
    static const sc_lv<68> ap_ST_fsm_state22;
    static const sc_lv<68> ap_ST_fsm_state23;
    static const sc_lv<68> ap_ST_fsm_state24;
    static const sc_lv<68> ap_ST_fsm_state25;
    static const sc_lv<68> ap_ST_fsm_state26;
    static const sc_lv<68> ap_ST_fsm_state27;
    static const sc_lv<68> ap_ST_fsm_state28;
    static const sc_lv<68> ap_ST_fsm_state29;
    static const sc_lv<68> ap_ST_fsm_state30;
    static const sc_lv<68> ap_ST_fsm_state31;
    static const sc_lv<68> ap_ST_fsm_state32;
    static const sc_lv<68> ap_ST_fsm_state33;
    static const sc_lv<68> ap_ST_fsm_state34;
    static const sc_lv<68> ap_ST_fsm_state35;
    static const sc_lv<68> ap_ST_fsm_state36;
    static const sc_lv<68> ap_ST_fsm_state37;
    static const sc_lv<68> ap_ST_fsm_state38;
    static const sc_lv<68> ap_ST_fsm_state39;
    static const sc_lv<68> ap_ST_fsm_state40;
    static const sc_lv<68> ap_ST_fsm_state41;
    static const sc_lv<68> ap_ST_fsm_state42;
    static const sc_lv<68> ap_ST_fsm_state43;
    static const sc_lv<68> ap_ST_fsm_state44;
    static const sc_lv<68> ap_ST_fsm_state45;
    static const sc_lv<68> ap_ST_fsm_state46;
    static const sc_lv<68> ap_ST_fsm_state47;
    static const sc_lv<68> ap_ST_fsm_state48;
    static const sc_lv<68> ap_ST_fsm_state49;
    static const sc_lv<68> ap_ST_fsm_state50;
    static const sc_lv<68> ap_ST_fsm_state51;
    static const sc_lv<68> ap_ST_fsm_state52;
    static const sc_lv<68> ap_ST_fsm_state53;
    static const sc_lv<68> ap_ST_fsm_state54;
    static const sc_lv<68> ap_ST_fsm_state55;
    static const sc_lv<68> ap_ST_fsm_state56;
    static const sc_lv<68> ap_ST_fsm_state57;
    static const sc_lv<68> ap_ST_fsm_state58;
    static const sc_lv<68> ap_ST_fsm_state59;
    static const sc_lv<68> ap_ST_fsm_state60;
    static const sc_lv<68> ap_ST_fsm_state61;
    static const sc_lv<68> ap_ST_fsm_state62;
    static const sc_lv<68> ap_ST_fsm_state63;
    static const sc_lv<68> ap_ST_fsm_state64;
    static const sc_lv<68> ap_ST_fsm_state65;
    static const sc_lv<68> ap_ST_fsm_state66;
    static const sc_lv<68> ap_ST_fsm_state67;
    static const sc_lv<68> ap_ST_fsm_state68;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_2C;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<32> ap_const_lv32_28;
    static const sc_lv<32> ap_const_lv32_3C;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_30;
    static const sc_lv<32> ap_const_lv32_31;
    static const sc_lv<32> ap_const_lv32_42;
    static const sc_lv<32> ap_const_lv32_43;
    static const sc_lv<32> ap_const_lv32_2D;
    static const sc_lv<32> ap_const_lv32_3F800000;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_40000000;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_29;
    static const sc_lv<32> ap_const_lv32_40;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_41B00000;
    static const sc_lv<64> ap_const_lv64_BFF0000000000000;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<8> ap_const_lv8_48;
    static const sc_lv<8> ap_const_lv8_7F;
    static const sc_lv<32> ap_const_lv32_80000000;
    static const sc_lv<32> ap_const_lv32_7FFFFFFF;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<8> ap_const_lv8_60;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<5> ap_const_lv5_4;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const3();
    void thread_ap_var_for_const2();
    void thread_ap_clk_no_reset_();
    void thread_abst_in_fu_196_p1();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state29();
    void thread_ap_CS_fsm_state30();
    void thread_ap_CS_fsm_state41();
    void thread_ap_CS_fsm_state42();
    void thread_ap_CS_fsm_state45();
    void thread_ap_CS_fsm_state46();
    void thread_ap_CS_fsm_state49();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state50();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state61();
    void thread_ap_CS_fsm_state64();
    void thread_ap_CS_fsm_state65();
    void thread_ap_CS_fsm_state67();
    void thread_ap_CS_fsm_state68();
    void thread_ap_CS_fsm_state7();
    void thread_ap_NS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_resultf_4_phi_fu_76_p10();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_grp_exp_generic_double_s_fu_89_ap_start();
    void thread_grp_fu_100_opcode();
    void thread_grp_fu_100_p0();
    void thread_grp_fu_100_p1();
    void thread_grp_fu_112_p0();
    void thread_grp_fu_112_p1();
    void thread_or_cond_fu_220_p2();
    void thread_p_1_fu_238_p3();
    void thread_p_Result_9_fu_188_p3();
    void thread_p_Val2_3_fu_258_p1();
    void thread_p_Val2_s_fu_156_p1();
    void thread_p_s_fu_298_p3();
    void thread_tmp_12_fu_294_p1();
    void thread_tmp_12_neg_fu_288_p2();
    void thread_tmp_12_to_int_fu_284_p1();
    void thread_tmp_15_fu_184_p1();
    void thread_tmp_1_fu_123_p0();
    void thread_tmp_3_fu_226_p2();
    void thread_tmp_4_fu_246_p1();
    void thread_tmp_4_neg_fu_232_p2();
    void thread_tmp_5_fu_315_p1();
    void thread_tmp_5_neg_fu_309_p2();
    void thread_tmp_5_to_int_fu_305_p1();
    void thread_tmp_6_fu_138_p2();
    void thread_tmp_7_fu_208_p2();
    void thread_tmp_9_fu_214_p2();
    void thread_tmp_V_1_fu_178_p1();
    void thread_tmp_V_2_fu_262_p4();
    void thread_tmp_V_fu_168_p4();
    void thread_tmp_fu_202_p2();
    void thread_tmp_i_30_fu_278_p2();
    void thread_tmp_i_fu_272_p2();
    void thread_tmp_s_fu_133_p2();
    void thread_x_2_fu_250_p3();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
